spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
org:
  jobrunr:
    job-scheduler:
      enabled: true
    background-job-server:
      enabled: true
#    dashboard:
#      enabled: true
#      port: 8201
server:
  port: 8889